image: docker.io/kentsday/dfx_rust:bullseye-dfx-0.10.1-gitpod-1
tasks:
  - name: dfx dev
    init: |
      . ~/fix_gitpod_path.sh
      cd src
      
      # ./start.sh
      # ./sh_setup_dev.sh
      # ./sh_reinstall.sh
      # dfx stop
    command: |
      . ~/fix_gitpod_path.sh
      cd src
      ./start_clean.sh
      ./sh_setup_dev.sh
      ./sh_build.sh
ports:
  - port: 8000
    visibility: public
    onOpen: ignore
vscode:
  extensions:
    - GitHub.copilot
    - panicbit.cargo
    - bungcip.better-toml
    - usernamehw.errorlens
    - ms-azuretools.vscode-docker
    - pmneo.tsimporter
    - rust-lang.rust
    - esbenp.prettier-vscode
    - alexkrechik.cucumberautocomplete
jetbrains:
  pycharm:
    plugins:
      - org.rust.lang
      - ru.adelf.idea.dotenv
      - com.chrisrm.idea.MaterialThemeUI
      - com.mallowigi